#!/usr/bin/env sh

has() {
  cat "$db" | grep --quiet "${page}\$"
}

extract() {
  cat "$db" |
    grep "${page}\$" |
    sed \
      -e 's_ :: .*__' \
      -e 's_^_#_'
}

run(){
  local db="$1" ; shift
  local com="$1" ; shift
  local page="$1" ; shift

  case $com in
    --has) has ;;
    --extract) extract ;;
  esac
}

run "$@"

