#!/usr/bin/env sh

run(){
	local db="$1" ; shift
	local page="$1" ; shift

	cat "$db"           |
	 grep "${page}\$"	|
	 sed                \
        -e 's_ :: .*__' \
        -e 's_^_#_'
}

run "$@"

