#!/usr/bin/env bash

# mwiki (through TUP) runs plugins inside it's mwiki directory.
MWIKI_DIR="."

page_mentions(){
	grep --recursive --only-matching '[#@][a-zA-Z0-9_\-]\+' "$MWIKI_DIR/entries/" |
	 sed "s_^$MWIKI_DIR/entries/__" |
     sed 's_.mw:_ :: _'             |
	 sort -u
}

page_mentions
