#!/usr/bin/env bash

process-line(){

	local type="$1" ; shift
	local date="$1" ; shift

	case "$type" in
		event|event-start)
			echo "- $date $@"
			;;
		event-end)
			echo "$@"
			return 1
			;;
	esac
}

join(){
	local dir="$1" ; shift
	local ext="$1" ; shift

	local temp=`mktemp`

	find "$dir" -type f -name "*$ext" -print0	|
	 LC_ALL=C sort --zero-terminated		|
	 xargs --null cat				|
	 while read event ; do

		local type="${event%% *}"
		event="${event#* }"		#remove the type
		local date="${event%% *}"
		local content="${event#* }"

		#echo "$type === $date === $content" >> /dev/stderr

		case $type in
			event)
				echo "- $date $content" >> "$temp"
				;;
			event-start)
				echo "- $date-~ $content" >> "$temp"
				;;
			event-end)
				sed --in-place --expression "s_^- \(..../../..\)-~ ${content}_- \1-${date} ${content}_" "$temp"
				;;
		esac
	 done

	cat "$temp"	
	 LC_ALL=C sort		|
	 awk '{ print $0 " <br> " }'

	rm "$temp"
}

join "$@"
