#!/usr/bin/env bash

process-line(){
	local type="$1" ; shift
	local date="$1" ; shift

	# there is a reason to put the dates at the end.
	# remember that dates do _not_ contain whitespace
	case "$type" in 
		event)
			echo "$@ $date"
			;;
		event-start)
			echo "$@ $date-~"
			;;
		event-end)
			echo "$@ ~-$date"
			;;
	esac
}

run(){
	local entry="$1"; shift
	local file="$1" ; shift

	local date=` echo "$entry" | sed 's_-_/_g' `

	cat "$file"		|
	 grep -E '^!event'	|
	 sed "s_^!event\(-start\|-end\)\?_event\\1 ${date}_"	|
	 while read line ; do
		process-line $line
	 done
}

run "$@"
