#!/bin/sh
(
	echo "<h1> $1 </h1><hr>"
	# this function is used to generate any sort of markdown/format file
	# to html output.
	cat "$1" |
	# [#@]			# match a '#' or '@' both are ok
	#     ( [a-zA-Z_0-9]+ )	# capture the part that matters
	sed 's_[#@]\([a-zA-Z_0-9]\+\)_<a href="\1.html">&</a>_g'
) |
awk '{ print $0 "<br>" }'
