#!/usr/bin/env bash

run-query(){
	if [ $# -eq 0 ]; then
		man search++
		exit
	fi

	# temporary storage file for index thing to show the user,
	tmp=`mktemp`

	# all of our arguments get passed to search++, since
	# the user should know how to query us.
	search++ --index-file build/swish++.index "$@" | awk ' /^#/ { print $0 ; next } { print $1 " " $4 " " $3 }' > "$tmp"

	# some of the files are temporary index files, strip out the
	# random temporary part, and use only their entry date
	dates=$(cat "$tmp" | awk '!/^#/ { gsub( /.mw$/, "", $2); print $2 }' | tr '\n' ' ' )

	if [ -t 1 ]; then
		# stdout is a terminal so we display the results before the actual entries
		sensible-pager "$tmp"
	fi

	# delete the temporary file, asap
	rm "$tmp"

	# display the entries
	journal view $dates
}

run-query "$@"
