#!/bin/sh

run(){
	( echo "<h1>Missing Pages</h1><hr>" ;
	 while [ $# -gt 0 ]; do
		local page="$1" ; shift
		cat "$page"
	 done |
	 sort -u |
	 sed 's_^.*$_<a href="./&.html">&</a>_' ) |
	awk '{ print $0 " <br>" }'
}

run "$@"
