#!/usr/bin/env bash

pages_linked_to(){
	local entry="$1" ; shift
	local file="$1" ; shift
	cat "$file"				|
	grep -o '[#@]\([a-zA-Z_0-9\-]\+\)'	|
	tr -d '#@'				|
	sort -u
}

pages(){
	mwiki entries |
	sort -u
}

run(){
	local page="$1" ; shift
	local file="$1" ; shift
	( pages_linked_to "$page" "$file" ; pages ; pages ) |
	# join the two lists
	sort |
	# show only unique entries, which gives us the pages that are missing
	uniq -u
}


run "$@"
