#!/usr/bin/env bash

# mwiki runs plugins inside it's .mwkik.d/ directory.
MWIKI_DIR="."

pages_linked_to(){
	local entry="$1" ; shift
	cat "$MWIKI_DIR/$entry.mw"		|
	grep -o '[#@]\([a-zA-Z_0-9]\+\)'	|
	tr -d '#@'				|
	sort -u
}

pages(){
	mwiki entries |
	sort -u
}

run(){
	local page="$1" ; shift
	( pages_linked_to "$page" ; pages ; pages ) |
	# join the two lists
	sort |
	# show only unique entries, which gives us the pages that are missing
	uniq -u
}


run "$@"
