#!/bin/sh

files() {
  # Get files from a directory.
  find "$MWIKI_DIR" -type f -iname '*.mw'
}

file_name() {
  # convert from file path to file name.
  sed -e 's_[^/]*/_#_g' -e 's_.mw$__'
}

create_dependencies() {
  # create a dependency between the output of whatever runs this to all
  # of the input files that get used to create this. This isn't exactly
  # correct, as it could be possible that some files don't get included
  # into the index, but we assume that `gen_index` does get them all.
  files | xargs -L 1 -I {} cat {} > /dev/null
}

section() {
  local title="$1" ; shift
  local order=""
  if [ "$1" = "--reverse" ]; then
    order="--reverse" ; shift
  fi

  if files | grep "$@" --quiet ; then
    echo "# $title"
    echo "---"
      files |
      grep "$@" |
      file_name |
      sort --unique $order
  fi
}

gen_index() {
  local DATE_FORMAT='/....-..-..\.mw$'
  local GENERATED='/~[^/]*\.mw$'
  section "Journal" --reverse "$DATE_FORMAT"
  section "Wiki" --invert-match -e "$DATE_FORMAT" -e "$GENERATED"
  section "Generated Pages" "$GENERATED" 
  section "Empty" "$^"
}

run() {
  MWIKI_DIR="$1" ; shift
  create_dependencies
  # this plugin directly invokes the html plugin
  gen_index | plugin.d/html/run
}

run "$@"
