#!/usr/bin/env bash

MWIKI_DIR="."

main() {
  grep --recursive --only-matching '^!tapestry:mention.\+' "${MWIKI_DIR}/entries/" |
    sed -e "s_^${MWIKI_DIR}/entries/__" -e 's_!tapestry:mention \+__' -e 's_.mw:_ :: _' |
    sort --unique
}

main
