#!/usr/bin/env bash

MWIKI_DIR="."

main() {
  grep --extended-regexp \
      --only-matching '^!tapestry:mention.+' \
      --recursive "${MWIKI_DIR}/entries/" |
    sed \
      --expression "s_^${MWIKI_DIR}/entries/__" \
      --expression 's_!tapestry:mention \+__' \
      --expression 's_.mw:_ :: _' |
    sort --unique
}

main
