#!/usr/bin/env bash

get_quotes(){
	grep -E '^!quotes ' --recursive "entries/" |
	# remove the quote specifier
	sed 's_^entries/\(.\+\)\.mw:!quotes \+\(.\+\)_\2\\n(#\1)_'
}

format_quotes(){
	# put space between quotes
	sed 's_$_\n_'				|
	# do some string replacement for quotes
	sed 's_\\n_\n\&nbsp;\&nbsp;_g'
}

run(){
  echo "# ~quotes"
  echo "---------"
	get_quotes	|
	format_quotes
}

run "$@"
