#!/usr/bin/env bash

pages_linked_to(){
	mwiki entries				|
	while read entry ; do
		cat "entries/$entry.mw"
	done					|
	grep -o '[#@]\([a-zA-Z_0-9\-]\+\)'	|
	tr -d '#@'				|
	sort -u
}

pages(){
	mwiki entries |
	sort -u
}

run(){
	( pages_linked_to ; pages ; pages ) |
	# join the two lists
	sort |
	# show only unique entries, which gives us the pages that are missing
	uniq -u
}


run "$@"
