#!/usr/bin/env sh

main(){
  ENTRY="$1" ; shift

  echo "# $ENTRY"
  # Underline the title, all of it. This looks really
  # good if you look at the markdown intermediary.
  echo "# $ENTRY" | sed 's|.|-|g'

  cat "entries/$ENTRY.mw" | plugin.d/tapestry/transform --convert

  plugin.d/tapestry/render partial/core-tapestry "$ENTRY"

  # Don't add mentions if there aren't any.
  plugin.d/mentions/extractor partial/core-mentions --has "$ENTRY" \
    && echo '---' \
    && echo '## Mentions' \
    && plugin.d/mentions/extractor partial/core-mentions --extract "$ENTRY" \
    || true
}

main "$@"
