#!/usr/bin/env sh
ENTRY="$1" ; shift

cat entries/$ENTRY.mw

echo

#
plugin.d/mentions/extractor partial/core-mentions --has $ENTRY \
  && echo '---' \
  && echo '# Mentions' \
  && plugin.d/mentions/extractor partial/core-mentions --extract $ENTRY

exit 0
