#!/usr/bin/env bash

run(){
	local entry="$1"; shift
	local file="$1" ; shift

	local date=` echo "$entry" | sed 's_-_/_g' `

	cat "$file"		|
	 grep -E '^!event'	|
	 sed "s_^!event\(-start\|-end\)\?_event\\1 ${date}_"
}

run "$@"
