#!/bin/sh

cd "$(journal config journal location)"

git diff --quiet

if [ $? -ne 0 ]; then
	git add .
	git commit
fi

# Exit with zero because we may fail to commit, but we don't want journal to
# worry about it.
exit 0
