#!/usr/bin/env bash

main() {
  local FILE="$( journal config journal location )/plugin.d/journal/last-journal-entry"

  aspell check "$FILE"

  if [ -e "${FILE}.bak" ]; then
    rm "$FILE.bak"
  fi
}

main
